name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make photo
      run: |
        python make-photo.py -u ${{ secrets.GITHUB_USER_ID }}
    - name: Upload photo as artifact
      uses: actions/upload-artifact@v1
      with:
          name: grass
          path: work/grass.png
